### ISSUE TITLE
Define *what* we are finding sources for

### ISSUE THREAD

**Issue by chexxor** [chexxor/purescript-documentation-discussion#9]
I can't find a place here which defines *what* the sources should be about. What should the common thread or topic about the sources be? I think this answer will be related to the problem statement that this project is addressing.

**Comment by JordanMartinez** [comment]
Good question. Ideally, it's focused purely on documentation. However, I think what we're really trying to do is make the language more accessible to new learners. Sometimes, the issue is just installing the language and finding resources. Other times it's explaining what some concept is. Other times, it's correcting 'myths' people believe.

I guess what we are not trying to do (at least not currently in this project) is identify ways that Purescript's ecosystem as a whole could become better (e.g. which libraries need to be written that aren't yet written, which need to be updated that aren't yet updated, etc.)

**Comment by chexxor** [comment]
That sounds right. So this project is about documenting **what PureScript currently is**, doing it in an efficient way, and choosing a reader-friendly way of organizing and displaying it. It isn't, then, deciding **what PureScript and its experience should be** (but it would be nice if that was improved, also).

**Comment by JordanMartinez** [comment]
Right. The 'what PS and its experience should be' could be a project that flows out of this one at a later point in time.

**Comment by chexxor** [comment]
I added a "Project Goals" section to the root README that should answer the original question in this issue. I think we can close this one.
